/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'polls': MotiaStream<{ id: string; title: string; options: Record<string, number>; deleted: boolean; deletedAt?: unknown }>
  }

  interface Handlers {
    'VotePoll': ApiRouteHandler<{ option: string; userId: string }, unknown, never>
    'verify-polls-stream': EventHandler<never, never>
    'CreatePoll': ApiRouteHandler<{ title: string; options: Array<string> }, unknown, never>
  }
    
}